### PR TITLE
Creating database naming conventions

### PR DESCRIPTION
**Pull request by diogob**
This would keep all current standards except for switching table names to singular form.
Singular is easier to write, read and it composes better (e.g. `Order` and `OrderDetail` instead of `Orders` and `OrderDetails`)

Having said that, I would be ok switching things around. We have 3 options:

1. Keep the current PR form: snake_case all the way down
2. Switch to prisma recommended defaults (PascalCase for models and camelCase for attributes).
3. Keep snake_case in the database level and use Prisma `@map` and `@@map` functions to map names to PascalCase and camelCase when they transition from database to the TS land

Thoughts?

### CODE REVIEW

**Review by giovanisleite — COMMENTED** [review]
I don't know how big is the work of choosing **the third option**, but IMHO is the best option because follows the naming convention of both environments (database e node/js/typescript).

**Comment by diogob** [comment]
@giovanisleite it's not a lot of work, just an annotation on fields and models that require translation. It also follows the lead of croods (that already has this translation feature built in).

**Comment by gustavoguichard** [comment]
I'd also vote on the third option, no snake_case in JS land but no camelCase on Postgres area either

**Comment by diogob** [comment]
The people have spoken!

**Pull request merged**
