### PR TITLE
Separate essential domain logic for tasks from framework logic

### PR DESCRIPTION
**Pull request by diogob**
This PR emerged from my attempt at creating some auth logic.
Before we start coding another subdomain (such as authentication) it's handy to have all reusable framework logic into a separate file such as `prelude.ts`.
Most of this functionality won't need to be exported, so we keep the domain's index as the single interface to all domain logic.
I have also moved the essential domain logic for tasks into it's own module.
We can now code another subdomain using a similar pattern:
1. Produce all actions implementing the logic in a new module (e.g. `auth`)
2. Import actions and types and consume then in the index, re-exporting types as needed.
3. Raw `Actions` should never be exported from the domain module since we want to hide that data structure.

I guess the rules I'm trying to enforce here are:
* Functions that produce the type `Action` can only be used inside the domain module so that is the only place in the application where domain logic is implemented.
* Function that consume the type `Action` outside of the domain must always use some interface (e.g. `findAction`) to navigate the domain logic so we keep the framework and the developers freedom to structure the domain logic as they see fit.

TODO:
- [x] Attempt to avoid de-structuring the `Action` in the `[...actionPath]` so we keep the type opaque.
- [ ] Create `internals` submodule on `domain-logic` to indicate what developers usually do not want to touch.
- [x] Check [Passport](https://www.passportjs.org/) as authentication method

### CODE REVIEW

**Comment by gustavoguichard** [comment]
I liked the approach, specially for the resulting API.
I don't see the reason for the second rule yet though..
I want to try helping with your missing Todo, where is that de-structuring happening in the code?

**Comment by diogob** [comment]
The second rule is to allow us to change the internal representation for `Action` (e.g. change transport to a list, or to a nested record) and `Actions`. As long as we use only function accessors we are free to change the implementation without breaking backwards compatibility. Given that we are able to preserve the function interface.

**Comment by diogob** [comment]
The de-structuring is on [this line of the makeHandler function](https://github.com/diogob/dx-experiment/blob/main/ui/pages/api/croods/%5B...actionPath%5D.ts#L9). Ideally we have one function that will encapsulate the 3 steps:
1. use the parser to parse the input.
2. call and await for the action result.
3. call the success or error lambda depending on the result.

**Comment by diogob** [comment]
I gave up creating the `internals` since it requires some tweaking in TS compilation and I believe it's not such a big priority. I'm merging this as is so we can move on.

**Pull request merged**
